name: docker-container

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-aci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Container Instance
        uses: azure/CLI@v1
        with:
          azcliversion: 2.59.0
          working-directory: modules/docker-container
          inlineScript: |
            az container create \
              --resource-group ResourceGroup1 \
              --name scontainer1 \
              --image ubuntu:latest \
              --cpu 1 \
              --memory 1.5 \
              --dns-name-label aci-demo-nginx \
              --ports 80 \
              --environment-variables ENV=prod SECRET_KEY=${{ secrets.SECRET_KEY }} \
              --command-line "sleep infinity"
