name: user and blob module

#on:
#  push:
#    branches:
#      - mai
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraformjob:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
# blob pipeline
      - name: Terraform Init
        run: terraform init
        working-directory: "modules/blobmodule"

      - name: Terraform Plan
        run: terraform plan
        working-directory: "modules/blobmodule"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "modules/blobmodule"
# user pipeline below
      - name: Terraform Init
        run: terraform init
        working-directory: "modules/usermodule/testmodule"

      - name: Terraform Plan
        run: terraform plan
        working-directory: "modules/usermodule/testmodule"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "modules/usermodule/testmodule"
# role access pipleine below
      - name: Terraform Init
        run: terraform init
        working-directory: "modules/roleaccess"

      - name: Terraform Plan
        run: terraform plan
        working-directory: "modules/roleaccess"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "modules/roleaccess"